# Generated by Django 4.2.1 on 2023-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unmixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='instrument',
            field=models.CharField(default='BASS', max_length=200),
            preserve_default=False,
        ),
    ]
