# Generated by Django 4.2.1 on 2023-05-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unmixapp', '0003_track_created_at_track_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='task_id',
            new_name='track_id',
        ),
    ]
