# Generated by Django 4.2.1 on 2023-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unmixapp', '0006_alter_track_result_path_alter_track_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
